# GraphQL schema example
#
# https://gqlgen.com/getting-started/

# This is the new content for 'graph/schema.graphqls'
enum GenderEnum {
  MALE
  FEMALE
  NON_BINARY
  OTHER
  PREFER_NOT_TO_SAY
}

enum ChidGenderEnum {
  GIRL
  BOY
  OTHER
}

enum childActivity_levelEnum {
  LOW
  MEDIUM
  HIGH
}



type User {
  userID: ID!
  email: String!
  created_at: Time!
  profilePicture: String

  profile: Profile!

  bio: Bio!
}
 
type Profile {
  userID: ID!
  name: String!
  about: String!
  languages: [String!]!
	addressCity: String!
  lat: Float
  lon: Float
	childName: String!
	childAbout:  String!
	ChildInterests: [String!]!
  
  user: User!
}

type Bio {
  userID: ID!
	parentGender: GenderEnum!
	preferredDistance: Int
	childBirthday: String!
	childGender: ChidGenderEnum!
	childActivity_level: childActivity_levelEnum!
	limitations: [String]
	allergies: [String]
	play_styles: [String]

  user: User!
}

type LoginResponse {
  token: String!
  user: User!
}


type Query {
  user(userID: ID!): User
  profile(userID: ID!): Profile
  bio(userID: ID!): Bio
  me: User
  myBio: Bio
  myProfile: Profile
  recommendations(limit: Int = 10, offset: Int = 0): [User!]!
}

type Mutation {
  registerUser(email: String!, password: String!): User!
  loginUser(email: String!, password: String!): LoginResponse!

  updateProfile (
  userID: ID
  name: String
  about: String
  languages: [String]
	addressCity: String
  lat: Float
  lon: Float
	childName: String
	childAge:   Int
	childAbout:  String
	ChildInterests: [String]
  ):Profile

  updateBio (
  userID: ID
	parentGender: String
	preferredDistance: Int
	childBirthday: String
	childGender: String
	childActivity_level: String
	limitations: [String]
	allergies: [String]
	play_styles: [String]
  ):Bio
}

# This scalar is provided by gqlgen
scalar Time