package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"log"
	"matchme-server/database"
	"matchme-server/graph/model"
	"matchme-server/helpers"
	"matchme-server/middleware"
	"matchme-server/services"

	pgx "github.com/jackc/pgx/v5"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, email string, password string) (*model.User, error) {
	if !helpers.IsValidEmail(email) {
		return nil, fmt.Errorf("email is invalid, please provide a valid email")
	}
	if !helpers.IsUniqEmail(email) {
		return nil, fmt.Errorf("email already exists")
	}
	if !helpers.IsValidPassword(password) {
		return nil, fmt.Errorf("password should be at least 6 symbols, one letter")
	}

	hashedPassword, err := helpers.HashPassword(password)
	if err != nil {
		log.Println(err)
		return nil, fmt.Errorf("internal server error (hashing)")
	}

	id, createdAt, err := database.CreateUser(ctx, r.DB, email, hashedPassword)
	if err != nil {
		log.Println(err)
		return nil, fmt.Errorf("internal server error (db)")
	}

	_, profilePicture := database.GetUserNamePhotoURL(ctx, r.DB, id)

	//    Note: gqlgen models are pointers
	return &model.User{
		UserID:         id,
		Email:          email,
		CreatedAt:      createdAt,
		ProfilePicture: &profilePicture,
	}, nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, email string, password string) (*model.LoginResponse, error) {
	userID, pwHash, err := database.GetUserByEmail(ctx, r.DB, email)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("user does not exist")
	}

	if err != nil {
		return nil, fmt.Errorf("internal server error (db)")
	}

	if !helpers.IsCorrectPassword(pwHash, password) {
		return nil, fmt.Errorf("invalid email or password")
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	access, err := helpers.MakeAccessToken(userID)
	if err != nil {
		return nil, fmt.Errorf("internal server error(access token)")
	}

	return &model.LoginResponse{
		Token: access,
		User:  user,
	}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, name *string, about *string, languages []*string, addressCity *string, lat *float64, lon *float64, childName *string, childAbout *string, childInterests []*string) (*model.Profile, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("not authenticated")
	}

	// Convert []*string to []string for DB
	var langs []string
	for _, l := range languages {
		if l != nil {
			langs = append(langs, *l)
		}
	}

	var interests []string
	for _, i := range childInterests {
		if i != nil {
			interests = append(interests, *i)
		}
	}

	input := database.UpdateProfileInput{
		Name:           name,
		About:          about,
		AddressCity:    addressCity,
		Lat:            lat,
		Lon:            lon,
		ChildName:      childName,
		ChildAbout:     childAbout,
		Languages:      &langs,
		ChildInterests: &interests,
	}

	if err := database.UpdateProfile(ctx, r.DB, userID, input); err != nil {
		return nil, gqlerror.Errorf("failed to update profile: %v", err)
	}

	// Fetch the updated profile to return it
	dbProfile, err := database.GetUserProfile(ctx, r.DB, userID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to load updated profile: %v", err)
	}

	dbProfileCh, err := database.GetChildProfile(ctx, r.DB, userID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to load updated profile: %v", err)
	}

	// Convert DB struct to GraphQL model
	return &model.Profile{
		UserID:         dbProfile.UserID,
		Name:           &dbProfile.Name,
		About:          &dbProfile.About,
		Languages:      stringSliceToPtrSlice(dbProfile.Languages),
		AddressCity:    &dbProfile.AddressCity,
		Lat:            &dbProfile.Lat,
		Lon:            &dbProfile.Lon,
		ChildName:      &dbProfileCh.Name,
		ChildAbout:     &dbProfileCh.About_short,
		ChildInterests: stringSliceToPtrSlice(dbProfileCh.Interests),
	}, nil
}

// UpdateBio is the resolver for the updateBio field.
func (r *mutationResolver) UpdateBio(ctx context.Context, parentGender *model.GenderEnum, preferredDistance *int32, childBirthday *string, childGender *model.ChidGenderEnum, childActivityLevel *string, limitations []*string, allergies []*string, playStyles []*string) (*model.Bio, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("not authenticated")
	}

	// Convert []*string to []string for DB
	var limit []string
	for _, l := range limitations {
		if l != nil {
			limit = append(limit, *l)
		}
	}

	var allerg []string
	for _, i := range allergies {
		if i != nil {
			allerg = append(allerg, *i)
		}
	}

	var playst []string
	for _, i := range playStyles {
		if i != nil {
			playst = append(playst, *i)
		}
	}

	input := database.UpdateBioInput{
		ParentGender:       parentGender,
		PreferredDistance:  preferredDistance,
		ChildBirthday:      childBirthday,
		ChildGender:        childGender,
		ChildActivityLevel: childActivityLevel,
		Limitations:        &limit,
		Allergies:          &allerg,
		PlayStyles:         &playst,
	}

	if err := database.UpdateBio(ctx, r.DB, userID, input); err != nil {
		return nil, gqlerror.Errorf("failed to update profile: %v", err)
	}

	// Fetch the updated profile to return it
	dbProfile, err := database.GetUserProfile(ctx, r.DB, userID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to load updated profile: %v", err)
	}

	dbProfileCh, err := database.GetChildProfile(ctx, r.DB, userID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to load updated profile: %v", err)
	}

	// Convert DB struct to GraphQL model

	var birthdayStrPtr *string

	if !dbProfileCh.Birthday.IsZero() {
		tempStr := dbProfileCh.Birthday.Format("2006-01-02")
		birthdayStrPtr = &tempStr
	}

	var preferredDistPtr *int32
	if dbProfile.PreferredDistance != 0 {
		temp := int32(dbProfile.PreferredDistance) // 1. Convert int to int32
		preferredDistPtr = &temp                   // 2. Get a pointer to the int32
	}

	return &model.Bio{
		UserID:             dbProfile.UserID,
		ParentGender:       model.GenderEnum(dbProfile.Gender),
		PreferredDistance:  preferredDistPtr,
		ChildBirthday:      birthdayStrPtr,
		ChildGender:        model.ChidGenderEnum(dbProfileCh.Gender),
		ChildActivityLevel: model.ChildActivityLevelEnum(dbProfileCh.Activity_level),
		Limitations:        stringSliceToPtrSlice(dbProfileCh.Limitations),
		Allergies:          stringSliceToPtrSlice(dbProfileCh.Allergies),
		PlayStyles:         stringSliceToPtrSlice(dbProfileCh.Play_styles),
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*model.User, error) {
	_, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user.Profile = profile
	user.Bio = bio

	return user, nil
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, userID string) (*model.Profile, error) {
	_, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		// User is not logged in.
		return nil, gqlerror.Errorf("Not authenticated")
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile.User = user

	return profile, nil
}

// Bio is the resolver for the bio field.
func (r *queryResolver) Bio(ctx context.Context, userID string) (*model.Bio, error) {
	_, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio.User = user

	return bio, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user.Profile = profile
	user.Bio = bio

	return user, nil
}

// MyBio is the resolver for the myBio field.
func (r *queryResolver) MyBio(ctx context.Context) (*model.Bio, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio.User = user

	return bio, nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*model.Profile, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		// User is not logged in.
		return nil, gqlerror.Errorf("Not authenticated")
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile.User = user

	return profile, nil
}

// Recommendations is the resolver for the recommendations field.
func (r *queryResolver) Recommendations(ctx context.Context, limit *int32, offset *int32) ([]*model.User, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("unauthorized")
	}

	// 3. Profile Completion Check (Same as before)
	percent, err := database.GetProfileCompletionPercent(ctx, r.DB, userID)
	if err != nil {
		log.Println(err)
		return nil, gqlerror.Errorf("db error")
	}

	if percent < 100 {
		return nil, gqlerror.Errorf("Profile filled only %.1f%% — please complete your profile before viewing recommendations.", percent)
	}

	currentProfile, err := database.GetMatchingProfile(ctx, r.DB, userID)
	if err != nil || currentProfile == nil {
		log.Println(err)
		return nil, gqlerror.Errorf("db error")

	}

	currentPrefs, err := database.GetUserMatchingPreferences(ctx, r.DB, userID)
	if err != nil {
		log.Println(err)
		return nil, gqlerror.Errorf("db error")

	}

	candidates, err := database.GetPotentialMatches(ctx, r.DB, userID)
	if err != nil {
		log.Println(err)
		return nil, gqlerror.Errorf("db error")

	}
	matches := services.CalculateMatchingScores(currentProfile, currentPrefs, candidates, ctx)

	if len(matches) > 10 {
		matches = matches[:*limit]
	}

	var recommendations []string

	for _, match := range matches {
		recommendations = append(recommendations, string(match.UserID))
	}

	var users []*model.User

	for _, recommendedUserId := range recommendations {
		user, err := r.GetUser(ctx, recommendedUserId)
		if err != nil {
			return nil, err
		}

		profile, err := r.GetProfile(ctx, userID)
		if err != nil {
			return nil, err
		}

		bio, err := r.GetBio(ctx, userID)
		if err != nil {
			return nil, err
		}

		user.Profile = profile
		user.Bio = bio
		users = append(users, user)
	}

	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
