package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"log"
	"matchme-server/database"
	"matchme-server/graph/model"
	"matchme-server/helpers"
	"matchme-server/middleware"

	pgx "github.com/jackc/pgx/v5"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, email string, password string) (*model.User, error) {
	if !helpers.IsValidEmail(email) {
		return nil, fmt.Errorf("email is invalid, please provide a valid email")
	}
	if !helpers.IsUniqEmail(email) {
		return nil, fmt.Errorf("email already exists")
	}
	if !helpers.IsValidPassword(password) {
		return nil, fmt.Errorf("password should be at least 6 symbols, one letter")
	}

	hashedPassword, err := helpers.HashPassword(password)
	if err != nil {
		log.Println(err)
		return nil, fmt.Errorf("internal server error (hashing)")
	}

	id, createdAt, err := database.CreateUser(ctx, r.DB, email, hashedPassword)
	if err != nil {
		log.Println(err)
		return nil, fmt.Errorf("internal server error (db)")
	}

	_, profilePicture := database.GetUserNamePhotoURL(ctx, r.DB, id)

	//    Note: gqlgen models are pointers
	return &model.User{
		UserID:         id,
		Email:          email,
		CreatedAt:      createdAt,
		ProfilePicture: &profilePicture,
	}, nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, email string, password string) (*model.LoginResponse, error) {
	userID, pwHash, err := database.GetUserByEmail(ctx, r.DB, email)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("user does not exist")
	}

	if err != nil {
		return nil, fmt.Errorf("internal server error (db)")
	}

	if !helpers.IsCorrectPassword(pwHash, password) {
		return nil, fmt.Errorf("invalid email or password")
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	access, err := helpers.MakeAccessToken(userID)
	if err != nil {
		return nil, fmt.Errorf("internal server error(access token)")
	}

	return &model.LoginResponse{
		Token: access,
		User:  user,
	}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, userID *string, name *string, about *string, languages []*string, addressCity *string, lat *float64, lon *float64, childName *string, childAge *int32, childAbout *string, childInterests []*string) (*model.Profile, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// UpdateBio is the resolver for the updateBio field.
func (r *mutationResolver) UpdateBio(ctx context.Context, userID *string, parentGender *string, preferredDistance *int32, childBirthday *string, childGender *string, childActivityLevel *string, limitations []*string, allergies []*string, playStyles []*string) (*model.Bio, error) {
	panic(fmt.Errorf("not implemented: UpdateBio - updateBio"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*model.User, error) {
	_, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user.Profile = profile
	user.Bio = bio

	return user, nil
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, userID string) (*model.Profile, error) {
	_, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		// User is not logged in.
		return nil, gqlerror.Errorf("Not authenticated")
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile.User = user

	return profile, nil
}

// Bio is the resolver for the bio field.
func (r *queryResolver) Bio(ctx context.Context, userID string) (*model.Bio, error) {
	_, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio.User = user

	return bio, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx) 
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user.Profile = profile
	user.Bio = bio

	return user, nil
}

// MyBio is the resolver for the myBio field.
func (r *queryResolver) MyBio(ctx context.Context) (*model.Bio, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio.User = user

	return bio, nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*model.Profile, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		// User is not logged in.
		return nil, gqlerror.Errorf("Not authenticated")
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile.User = user

	return profile, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
