package database

import (
	"context"
	"database/sql"
	"fmt"
	"time"
	"todo/internal/types"
)

// when registering, insert first data into app_user table
func (tx *Tx) RegisteringNewUser(ctx context.Context, reg *types.Register, tap *types.AppUser) error {
	cost := 12

	ctxInsert, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()

	query := `
		INSERT INTO app_user (
			email,
			name,
			password_hash
		)
		VALUES (
			$1,
			$2,
			make_bcrypt_hash($3, $4)
		)
		RETURNING id;
	`

	err := tx.Tx.QueryRow(ctxInsert, query, reg.Email, reg.Name, reg.Password, cost).Scan(&tap.Id)
	if err != nil {
		return fmt.Errorf("RegisteringNewUser: %w", err)
	}

	tap.Name = reg.Name
	tap.Email = reg.Email

	return nil
}

// when login, insert data into persistance table
func (tx *Tx) Login(ctx context.Context, log *types.Login, pers *types.Persistance) error {
	ctxInsert, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()

	query := `
		WITH u AS (
			SELECT id, password_hash
			FROM app_user
			WHERE email = $1
		)
  		INSERT INTO persistance (user_id, token, login_at, logout_at)
  		SELECT u.id, gen_random_uuid(), $3, NULL
  		FROM u
  		WHERE bcrypt_check($2, u.password_hash)
		ON CONFLICT (user_id) DO UPDATE
			SET token = gen_random_uuid(), login_at = $3, logout_at = NULL
		RETURNING user_id, token, login_at;
	`

	err := tx.Tx.QueryRow(ctxInsert, query,
		log.Email,    // $1
		log.Password, // $2
		pers.LoginAt, // $3
	).Scan(&pers.UserId, &pers.Token, &pers.LoginAt)
	if err != nil {
		return fmt.Errorf("Login: %w", err)
	}

	return nil
}

// inserting data into table todo on first todo input
func (tx *Tx) InsertIntoTableTodo(ctx context.Context, t *types.Todo) error {
	ctxInsert, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()

	var dueTime sql.NullTime
	if !t.DueTime.IsZero() || t.DueTime.Compare(time.Now()) >= 1 {
		dueTime = sql.NullTime{Time: t.DueTime, Valid: true}
	} else {
		dueTime = sql.NullTime{Valid: false}
	}

	query := `
		INSERT INTO todo (
			user_id,
			content,
			created_at,
			due_time
			-- is_plan -- skip this due to autogenerated
		)
		VALUES (
			$1, $2, $3, $4
		)
		RETURNING id, is_plan;
	`

	err := tx.Tx.QueryRow(ctxInsert, query,
		t.UserId,
		t.Content,
		t.CreatedAt,
		dueTime,
	).Scan(&t.Id, &t.IsPlan)

	if err != nil {
		return fmt.Errorf("insert into table todo: %v", err)
	}

	return nil
}

// // inserting data into table chat on each chat
// func (tx *Tx) InsertIntoTableChat(ctx context.Context, c *types.Chat) error {
// 	ctxInsert, cancel := context.WithTimeout(ctx, 3*time.Second)
// 	defer cancel()

// 	return nil
// }

// // inserting data into table connected when request for a friend
// func (tx *Tx) InsertIntoTableConnected(ctx context.Context, con *types.Connected) error {
// 	ctxInsert, cancel := context.WithTimeout(ctx, 3*time.Second)
// 	defer cancel()

// 	return nil
// }
